= Contributing to Jakarta Data
:toc: auto

Thanks for your interest in this project.

== Project description

Jakarta Data provides an API that makes data access easy. A
Java developer can split the persistence from the model with several features,
such as the ability to compose custom query methods on a Repository interface where the framework
will implement it.

References:

* https://github.com/eclipse-ee4j/jpa-api/issues/294
* https://spring.io/projects/spring-data
* https://deltaspike.apache.org/documentation/jpa.html
* https://github.com/eclipse-ee4j/nosql/blob/master/spec/src/main/asciidoc/repository.adoc
* https://micronaut-projects.github.io/micronaut-data/latest/guide/index.html


* https://projects.eclipse.org/projects/ee4j.data

== Terms of Use

This repository is subject to the Terms of Use of the Eclipse Foundation

* http://www.eclipse.org/legal/termsofuse.php

== Developer resources

Information regarding source code management, builds, coding standards, and
more.

* https://projects.eclipse.org/projects/ee4j.data/developer

The project maintains the following source code repositories

* https://github.com/jakartaee/data-api

== Eclipse Development Process

This Eclipse Foundation open project is governed by the Eclipse Foundation
Development Process and operates under the terms of the Eclipse IP Policy.

The Jakarta EE Specification Committee has adopted the Jakarta EE Specification
Process (JESP) in accordance with the Eclipse Foundation Specification Process
v1.2 (EFSP) to ensure that the specification process is complied with by all
Jakarta EE specification projects.

* https://eclipse.org/projects/dev_process
* https://www.eclipse.org/org/documents/Eclipse_IP_Policy.pdf
* https://jakarta.ee/about/jesp/
* https://www.eclipse.org/legal/efsp_non_assert.php

== Eclipse Contributor Agreement

In order to be able to contribute to Eclipse Foundation projects you must
electronically sign the Eclipse Contributor Agreement (ECA).

* http://www.eclipse.org/legal/ECA.php

The ECA provides the Eclipse Foundation with a permanent record that you agree
that each of your contributions will comply with the commitments documented in
the Developer Certificate of Origin (DCO). Having an ECA on file associated with
the email address matching the "Author" field of your contribution's Git commits
fulfills the DCO's requirement that you sign-off on your contributions.

For more information, please see the Eclipse Committer Handbook:
https://www.eclipse.org/projects/handbook/#resources-commit

== Contact

Contact the project developers via the project's "dev" list.

* https://accounts.eclipse.org/mailing-list/data-dev

=== Developer Certificate of Origin - DCO

This is a security layer for the project and for the developers. It is mandatory.

Follow one of these two methods to add DCO to your commits:

==== 1. Command line

Follow the steps:
**Step 1:** Configure your local git environment adding the same name and e-mail configured at your GitHub account. It helps to sign commits manually during reviews and suggestions.

[source, Bash]
----
git config --global user.name “Name”
git config --global user.email “email@domain.com.br”
----

**Step 2:** Add the Signed-off-by line with the `'-s'` flag in the git commit command:

[source, Bash]
----
$ git commit -s -m "This is my commit message"
----

==== 2. GitHub website

You can also manually sign your commits during GitHub reviews and suggestions, follow the steps below:

**Step 1:** When the commit changes box opens, manually type or paste your signature in the comment box, see the example:

[source, Bash]
----
Signed-off-by: Name < e-mail address >
----

== Contact

Contact the project developers via the project's "dev" list.

* https://dev.eclipse.org/mailman/listinfo/data-dev


== Issues

If you found a bug or have an idea, check out the following sections before submitting your contribution.

=== Check the issue tracker

All our issues are centralized in our https://github.com/jakartaee/data[**main repository**], it is quite likely that you will find a topic that is being discussed. Check the https://github.com/jakartaee/data/issues[**open issues**], another good way to start is https://github.com/jakartaee/data/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[**good first issues**].
