= Jakarta Data
:toc: auto

== Introduction

The Jakarta Data specification provides an API for easier data access. A Java developer can split the persistence from the model with several features, such as the ability to compose custom query methods on a Repository interface.

Jakarta Data’s goal is to provide a familiar and consistent, Jakarta-based programming model for data access while still retaining the particular traits of the underlying data store.

=== Repository

A repository abstraction aims to significantly reduce the boilerplate code required to implement data access layers for various persistence stores.

[source,java]
----
@Repository
public interface CarRepository extends CrudRepository<Car, Long> {

  List<Car> findByType(CarType type);

  Optional<Car> findByName(String name);

}
----


[source,java]
----
CarRepository repository ==//instance
Car ferrari = Car.id(10L).name("Ferrari").type(CarType.SPORT);
repository.save(ferrari);
----

==== Pagination

Jakarta Data also supports particular parameters to define pagination and sorting.

[source,java]
----

@Repository
public interface ProductRepository extends PageableRepository<Product, Long> {

 Page<Car> findByTypeOrderByName(CarType type, Pageable pageable);

}
----


=== Maven

Add the Maven dependency:

[source,xml]
----
<dependency>
  <artifactId>jakarta-data-api</artifactId>
  <groupId>jakarta.data</groupId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
----


== Code of Conduct

This project is governed by the Eclipse Foundation of Conduct. By participating, you are expected to uphold this code of conduct. Please report unacceptable behavior to codeofconduct@eclipse.org.

== Getting Help

Having trouble with Jakarta Data? We’d love to help!

Report bugs with Jakarta Data at https://github.com/jakartaee/data/issues.

== Building from Source

You don’t need to build from source to use the project, but you can do so with Maven and Java 11 or higher.

[source, Bash]
----
mvn clean install
----


== Meetings

=== Calendar
* Europe: 
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=Europe/Athens++[Eastern],
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=Europe/Berlin++[Central],
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=Europe/Lisbon++[Western]

* America: 
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=America/Toronto++[Eastern],
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=America/Chicago++[Central],
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=America/Denver++[Mountain],
link:++https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=America/Los_Angeles++[Pacific]

* https://docs.google.com/document/d/1MQbwPpbEBHiAHes1NaYTJQzEBGUYXxaJYw5K-yj053U/edit[Meetings Notes]
