:starterLoc: ../../starter

=== SE Mode

==== Standalone Dependencies

The runtime will need to be configured with the dependencies necessary to run the TCK.

Example se-pom.xml:

[source, xml]
----
include::{starterLoc}/se-pom.xml[tag=runtimeDep]
----

==== Configure {TCKTestPlatform}

{TCKTestPlatform} needs to be configured to know which packages contain tests to run.
This test discovery is done automatically by configuring a `dependenciesToScan` element.

In order for your maven project to execute these tests the surefire plugin needs to be configured.

Example se-pom.xml:

[source, xml]
----
include::{starterLoc}/se-pom.xml[tags=configJunit5;!logging;!signature;!entity]
----

==== Standalone Mode

All test classes that support running in standalone mode are annotated with the `@Standalone` annotation.

When running in standalone mode, include the group `<groups>standalone<groups>`.
This will ensure that none of the core/web/full profile tests are run.

When running in standalone mode, include the system property `<jakarta.tck.profile>none</jakarta.tck.profile>`.
This will ensure that no deployments are created and that all tests are run on the client JVM.

==== Entity Modes

All test classes in the TCK are annotated with `@NoSQL`, `@Persistence`, or `@AnyEntity` annotations.

If your {APILongName} implementation supports NoSQL entities, include the group `<groups>nosql<groups>`.

If your {APILongName} implementation supports Persistence entities, include the group `<groups>persistence<groups>`.

==== Filtering Tests
As mentioned in the prior sections tests can be filtered by modifying the `<groups>` element. 
It is recommended to avoid using `<excludedGroups>` as the surefire plugin has a known issue 
where excluded groups do not have precedence over included groups. 

Therefore, if you wanted to run standalone tests with a NoSQL entities you would 
configure `<groups><![CDATA[standalone & nosql]]><groups>`.

==== Standalone Logging

The {APILongName} TCK uses `java.util.logging` for logging debug messages, and to output test results in some cases.
This is done by pointing the JVM to the logging configuration file using the property.
An example logging configuration file has been provided under the `/starter` directory. 

To enable logging for the Client side of tests, add a system property to the surefire plugin:

Example se-pom.xml:

[source, xml]
----
include::{starterLoc}/se-pom.xml[tags=systemProperties;!signature;!standalone;!entity;!profile]
----
