:starterLoc: ../../starter

=== EE Mode

==== Test Client Dependencies

The entry point to running the TCK will be on the client-side using {TCKTestPlatform}. 
The Test Client will need to be configured with the dependencies necessary to run the TCK.
Some of these dependencies will depend on the application server you are using, and 
comments have been added to this sample describing the customization necessary.

Example ee-pom.xml:

[source, xml]
----
include::{starterLoc}/ee-pom.xml[tag=testClientDep]
----

Each of these Arquillian tests run within the runtime container, with the help of an Arquillian adapter for that runtime implementation (mentioned as a prerequisite).

==== Configure {TCKTestPlatform}

{TCKTestPlatform} needs to be configured to know which packages contain tests to run.
This test discovery is done automatically by configuring a `dependenciesToScan` element.

In order for your maven project to execute these tests the surefire plugin needs to be configured.

Example ee-pom.xml:

[source, xml]
----
include::{starterLoc}/ee-pom.xml[tags=configJunit5;!arquillian;!logging;!entity]
----

==== Profile Mode

All test classes that require running on a Jakarta profile are annotated with the `@Core`, `@Web`, or `@Full` annotation.

When running against a Jakarta profile, include the group that matches your supported profile. For example: `<groups>core<groups>`.

==== Entity Modes

All test classes in the TCK are annotated with `@NoSQL`, `@Persistence`, or `@AnyEntity` annotations.

If your {APILongName} implementation supports NoSQL entities, include the group `<groups>nosql<groups>`.

If your {APILongName} implementation supports Persistence entities, include the group `<groups>persistence<groups>`.

==== Filtering Tests
As mentioned in the prior sections tests can be filtered by modifying the `<groups>` element. 
It is recommended to avoid using `<excludedGroups>` as the surefire plugin has a known issue 
where excluded groups do not have precedence over included groups. 

Therefore, if you wanted to run core profile tests with a NoSQL entities you would 
configure `<groups>core & nosql<groups>`.

==== Configure Arquillian

Application Servers that implement the Arquillian SPI use a configuration file to define properties, such as hostname, port, username, password, etc.
These properties will allow Arquillian to connect to the application server, install applications, and get test responses.
An example Arquillian configuration file has been provided in the `starter/` directory.

It is possible to configure the surefire plugin to past variables to the Arquillian container:

[source, xml]
----
include::{starterLoc}/ee-pom.xml[tags=systemProperties;!logging;!signature;!standalone;!entity]
----

==== Configure Jakarta EE Platform Server

The {APILongName} TCK requires that your Jakarta EE Platform Server has a valid implementation of the {APILongName} API.

==== Configure Client and Server Logging

The {APILongName} TCK uses `java.util.logging` for logging debug messages, and to output test results in some cases.
Registered loggers exist both on the Test Client and Test Server meaning you will need to configure both sides to enable logging.
This is done by pointing the JVM to the logging configuration file using the property.
An example logging configuration file has been provided under the `/starter` directory. 

To enable logging for the Client side of tests, add a system property to the surefire plugin:

Example ee-pom.xml:

[source, xml]
----
include::{starterLoc}/ee-pom.xml[tags=systemProperties;!arquillian;!signature;!standalone;!entity]
----

To enable logging for the Server side of tests, set the same system property on the JVM running your application server.

==== Advanced Arquillian Configuration

Some application servers may have custom deployment descriptors that they would like to include 
as part of the applications that are being deployed to their server. 
The custom deployment descriptors can be included in a programmatic way using ShrinkWrap and the Arquillian SPI.

Example ApplicationArchiveProcessor:

[source, java]
----
include::{starterLoc}/src/main/java/ee/jakarta/tck/data/example/extension/MyApplicationArchiveProcessor.java[tags=applicationProcessor]
----

Example LoadableExtension:

[source, java]
----
include::{starterLoc}/src/main/java/ee/jakarta/tck/data/example/extension/MyLoadableExtension.java[tags=loadableExtension]
----

Example META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension:

[source, txt]
----
include::{starterLoc}/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension[]
----
