# This workflow automates the creation of Specification Documents
# which will be copied into https://github.com/jakartaee/specifications

name: Generate specification documentation

on: 
    workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Generate specification docs
      run: |
        mvn package --file api/pom.xml
        mvn package --file stateful/pom.xml
        mvn package --file spec/pom.xml
    - name: Assemble documentation
      run: |
        mkdir documentation/

        cp spec/target/generated-docs/jakarta-data.pdf \
          documentation/jakarta-data.pdf
        cp spec/target/generated-docs/jakarta-method-name-query.pdf \
           documentation/jakarta-method-name-query.pdf

        cp spec/target/generated-docs/jakarta-data.html \
           documentation/jakarta-data.html
        cp spec/target/generated-docs/jakarta-method-name-query.html \
           documentation/jakarta-method-name-query.html

        cp -r api/target/reports/apidocs/ \ 
              documentation/api/apidocs
        
        cp -r stateful/target/reports/apidocs/ \ 
              documentation/stateful/apidocs
    - name: Upload documentation
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Specification Documentation
        path: documentation/
        if-no-files-found: error